config/routes.rb
Gthkn::Application.routes.draw do

  resources :wikipages do
    resources :wiki_revisions, only: [:new, :create, :index]
  end

  devise_for :users

  resources :users
  resources :blogposts, :only => [:create, :edit, :update, :destroy, :index]
  resources :events
  resources :initiation_requirements, only: [:new, :create, :update]
  resources :auth_codes

  match '/admin/user_admin' => 'users#user_admin', :as => :user_admin
  match '/admin/user_admin/search' => 'users#user_admin_search', :as => :user_admin_search
  match '/admin/initiation' => 'promotions#initiation', as: :initiation

  match '/promotion/member_request/:id' => 'promotions#request_member_promotion',
    as: :member_promote_request
  match '/promotion/member' => 'promotions#member_promote', as: :member_promote

  match '/:controller(/:action(/:id))'

  match '/signup' => 'users#new', :as => :signup

  match '/new_blogpost' => 'blogposts#new', :as => :new_blogpost

  root :to => 'pages#home'
  match '/about' => 'pages#about', :as => :about
  match '/eventlist' => 'pages#events', :as => :eventlist
  match '/corporate' => 'pages#corporate', :as => :corporate
  match '/officers' => 'pages#officers', :as => :officers
  match '/contact' => 'pages#contact', :as => :contact
  match '/blog' => 'blogposts#index', :as => :blog

  match '/admin' => 'pages#admin', :as => :admin
end

app/models/auth_code.rb
# == Schema Information
#
# Table name: auth_codes
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  code       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class AuthCode < ActiveRecord::Base
  attr_accessible :code, :id, :name

  validates_presence_of :name, :code
  validates_uniqueness_of :name
end

app/controllers/auth_codes_controller.rb
include ApplicationHelper

class AuthCodesController < ApplicationController

  before_filter :deny_unless_officer

  def new
    @authcode = AuthCode.new
  end

  def create
    @authcode = AuthCode.new(params[:auth_code])
    if @authcode.save
      flash[:success] = "Auth Code created."
      redirect_to @authcode
    else
      flash[:error] = "There were some errors."
      render :new
    end
  end

  def destroy
    @authcode = AuthCode.find(params[:id])
    if @authcode.name != "initiate" and @authcode.name != "member"
      @authcode.delete
      redirect_to auth_codes_path
    else
      flash[:error] = "Cannot delete auth_code for #{@authcode.name}"
      redirect_to @authcode
    end
  end

  def edit
    @authcode = AuthCode.find(params[:id])
  end

  def update
    @authcode = AuthCode.find(params[:id])
    @authcode.code = params[:auth_code][:code]
    if @authcode.save
      flash[:notice] = "Authcode Changed."
      redirect_to @authcode
    else
      render 'edit'
    end
  end

  def index
    @authcodes = AuthCode.all
  end

  def show
    @authcode = AuthCode.find(params[:id])
  end

end

app/helpers/auth_code_helper.rb
module AuthCodeHelper
end

app/views/auth_codes/edit.html.haml
%h1= "Edit '#{@authcode.name}' Auth Code"

= form_for @authcode do |f|
  = f.label :code
  = f.text_field :code

  = f.submit 'Edit', class: 'btn btn-large btn-primary'

app/views/auth_codes/index.html.haml
%h1 Auth Codes

= link_to "New Auth Code", new_auth_code_path, class: "btn btn-primary btn-large"

.authcodes
  - @authcodes.each do |code|
    .row
      .span4.name= link_to code.name, code
      .span4.code= code.code
      .span1= link_to "Edit", edit_auth_code_path(code), class: "btn btn-info btn-small"
      - if (code.name != 'initiate' and code.name != 'member')
        .span1= link_to "Delete", code, method: :delete, class: "btn btn-danger btn-small"

app/views/auth_codes/new.html.haml
%h1 New Auth Code

.alert
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  There should be no reason to make a new auth code.
  Make sure you are doing this for the right reasons.

= form_for @authcode do |f|
  = f.label :name
  = f.text_field :name

  = f.label :code
  = f.text_field :code

  = f.submit 'Create', class: 'btn btn-large btn-primary'

app/views/auth_codes/show.html.haml
%h1 
  Auth Code: 
  = @authcode.name
%h2= @authcode.code

.buttons.row
  .span2= link_to "Edit", edit_auth_code_path(@authcode), class: 'btn btn-large btn-info'
  - if (@authcode.name != 'initiate' and @authcode.name != 'member')
    .span2= link_to "Delete", @authcode, method: :delete, class: 'btn btn-large btn-danger'