config/routes.rb
Gthkn::Application.routes.draw do

  resources :wikipages do
    resources :wiki_revisions, only: [:new, :create, :index]
  end

  devise_for :users

  resources :users
  resources :blogposts, :only => [:create, :edit, :update, :destroy, :index]
  resources :events
  resources :initiation_requirements, only: [:new, :create, :update]
  resources :auth_codes

  match '/admin/user_admin' => 'users#user_admin', :as => :user_admin
  match '/admin/user_admin/search' => 'users#user_admin_search', :as => :user_admin_search
  match '/admin/initiation' => 'promotions#initiation', as: :initiation

  match '/promotion/member_request/:id' => 'promotions#request_member_promotion',
    as: :member_promote_request
  match '/promotion/member' => 'promotions#member_promote', as: :member_promote

  match '/:controller(/:action(/:id))'

  match '/signup' => 'users#new', :as => :signup

  match '/new_blogpost' => 'blogposts#new', :as => :new_blogpost

  root :to => 'pages#home'
  match '/about' => 'pages#about', :as => :about
  match '/eventlist' => 'pages#events', :as => :eventlist
  match '/corporate' => 'pages#corporate', :as => :corporate
  match '/officers' => 'pages#officers', :as => :officers
  match '/contact' => 'pages#contact', :as => :contact
  match '/blog' => 'blogposts#index', :as => :blog

  match '/admin' => 'pages#admin', :as => :admin
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  email                  :string(255)
#  officer                :boolean
#  initiate               :boolean
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string(255)
#  salt                   :string(255)
#  show_email             :boolean
#  officer_position       :string(255)
#  remember_token         :string(255)
#  member                 :boolean
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  avatar_url             :string(255)
#

require 'digest'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :officer, :initiate, :member,\
           :password_confirmation, :show_email, :officer_position, :avatar
   
  default_scope :order => 'email ASC'
  
  has_many :blogposts
  has_and_belongs_to_many :events
  has_one :initiation_requirement
  has_many :wiki_revisions
  
  # Validations
  
  validates_confirmation_of :password, :on => :create
  validates_presence_of :password, :on => :create
  
  email_regex = /\A[\w+\-.]+@(.*)?gatech.edu\z/i
  
  validates_presence_of :name, :email
  validates_length_of :name, :maximum => 50
  validates_format_of :email, :with => email_regex
  validates_uniqueness_of :email, :case_sensitive => false

  after_initialize :set_default_values

    
  def set_default_values
    self.initiate = false if self.initiate.nil?
    self.officer = false if self.officer.nil?
    self.member = false if self.member.nil?
    self.show_email = false if self.show_email.nil?
    return true
  end
  
  def self.search(search, type)
    if (search)
      if (type)
        find(:all, :conditions => ["#{type} LIKE ?", "%#{search}%"])
      else
        find(:all, :conditions => ["email LIKE ?", "%#{search}%"])
      end
    else
      find(:all)
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :only => [:edit, :update]
  before_filter :correct_user_or_officer, :only => [:edit, :update]
  before_filter :deny_unless_officer, :only =>[:user_admin]
  
  def show
    redirect_to root_path if params[:id] == "sign_out"
    @user = User.find(params[:id])
    @title = @user.name
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def user_admin
    @users = User.paginate(:page => params[:page], :per_page => 40)
    @title = "User Admin"
  end
  
  def user_admin_search
    @users = User.search(params[:search], params[:type])
    @title = "Admin Search Results"
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user == @user
  end

  private

    def correct_user_or_officer
      if !current_user.officer
        correct_user
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def comps_format(completed)
    if completed == true
      "Completed"
    else
      "Still Required"
    end
  end
end

app/views/users/_user_admin_list.html.erb
<div class="users-list">
	<% @users.each do |user| %>
      <div class="row">
			 <div class="span3 offset3 right"><%= link_to user.name, user %></div>
       <div class="span3"><%= mail_to user.email, nil, encode: 'javascript' %> </div>
      </div>

	<% end %>
</ul>

app/views/users/_user_search_form.html.erb
<div class="user_search round">
	<%= form_tag user_admin_search_path, :method => 'get' do %>
		<div class="search_field">
			<%= label_tag "Search for a user:" %>
			<%= text_field_tag :search %>
		</div>
		<div class="search_type">
			<%= label_tag "Email" %>
			<%= radio_button_tag :type, "email" %>
			<%= label_tag "Name" %>
			<%= radio_button_tag :type, "name" %>
		</div>
		<div class="submit">
			<%= submit_tag "Submit", :name => nil %>
		</div>
	<% end %>
</div>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.haml
%h1 Update your Profile
.row
	.span6.offset3
		%fieldset
			= form_for(@user) do |f|
				=render 'shared/user_error_messages'

				= f.label :name
				= f.text_field :name

				= f.label :email
				= f.text_field :email

				= f.label :show_email
				%lable
					= f.radio_button :show_email, true
					Yes
				%lable
					= f.radio_button :show_email, false
					No

				- if current_user_is_officer?
					= f.label :initiate
					%lable
						= f.radio_button :initiate, true
						Yes
					%lable
						= f.radio_button :initiate, false
						No

					= f.label :officer
					%lable
						= f.radio_button :officer, true
						Yes
					%lable
						= f.radio_button :officer, false
						No

				- if @user.officer
					= f.label :officer_position
					= f.text_field :officer_position

				.commit
					= f.submit "Save Changes", class: "btn btn-large btn-primary"

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user, :html => {:multipart => true}) do |f| %>
	<%= render 'shared/user_error_messages' %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	
	<div class="field">
		<%= f.label :avatar %>
		<%= f.file_field :avatar %>
	</div>
	
	<div class="field">
		<%= f.label :password %> <br />
		<%= f.password_field :password %>
 	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation"%><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="field">
		<%= f.submit "Sign up" %>
	</div>
<% end %>

app/views/users/show.html.haml
%h1= @user.name
- if @user.show_email
  .lable Email:
  = mail_to @user.email, nil, encode: 'javascript'
-if (user_signed_in? and @user == current_user) or current_user.officer
  .row.buttons
    .span2= link_to "Edit", edit_user_path(@user), class: 'btn btn-info btn-medium'
    - if not @user.initiate and not @user.member and not @user.officer
      .span2= link_to "Promote to Initiate", "/initiation_requirements/new/#{@user.id}", class: 'btn btn-primary btn-medium'
      .span2= link_to "Promote to Member", "/promotion/request_member_promotion/#{@user.id}", class: 'btn btn-primary btn-medium'

- if @user.member or @user.officer
  %h2 Events
  %ul.events
    - @user.events.each do |event|
      %li.event
        - if user_signed_in? and @user == current_user
          %span.attend-button= link_to "Unattend", "/events/unattend/#{event.id}", class: "btn btn-warning btn-medium"
        .title= link_to event.title, event
        .date= event.date_occurred

- if @user.initiate and not @user.initiation_requirement.nil?
  %h2 Initiation Requirements
  - requirement = @user.initiation_requirement
  .initiation-requirements 
    .row
      .span4.offset2.right Professor Invited
      - if requirement.professor_invited
        .span2.complete Complete
      - else
        .span2.incomplete Incomplete
    .row
      .span4.offset2.right Dues Paid
      - if requirement.dues_paid
        .span2.complete Recieved
      - else
        .span2.incomplete Not Yet Recieved
    .row
      .span4.offset2.right Lab Chip Packaging Party Attended
      - if requirement.lab_chip_party_attended
        .span2.complete Complete
      - else
        .span2.incomplete Incomplete
    .row
      .span4.offset2.right Service Project
      - if requirement.lab_chip_party_attended
        .span2.complete Recieved
      - else
        .span2.incomplete Not Yet Recieved

app/views/users/user_admin.html.erb
<h1>User Admin</h1>

<%= render 'user_search_form' %>

<%= will_paginate @users %>

<%= render 'user_admin_list' %>

<%= will_paginate @users %>

app/views/users/user_admin_search.html.erb
<h1>Search Results</h1>

<%= link_to "Back", user_admin_path %>

<%= render 'user_search_form' %>

<%= render 'user_admin_list' %>