config/routes.rb
Gthkn::Application.routes.draw do

  resources :wikipages do
    resources :wiki_revisions, only: [:new, :create, :index]
  end

  devise_for :users

  resources :users
  resources :blogposts, :only => [:create, :edit, :update, :destroy, :index]
  resources :events
  resources :initiation_requirements, only: [:new, :create, :update]
  resources :auth_codes

  match '/admin/user_admin' => 'users#user_admin', :as => :user_admin
  match '/admin/user_admin/search' => 'users#user_admin_search', :as => :user_admin_search
  match '/admin/initiation' => 'promotions#initiation', as: :initiation

  match '/promotion/member_request/:id' => 'promotions#request_member_promotion',
    as: :member_promote_request
  match '/promotion/member' => 'promotions#member_promote', as: :member_promote

  match '/:controller(/:action(/:id))'

  match '/signup' => 'users#new', :as => :signup

  match '/new_blogpost' => 'blogposts#new', :as => :new_blogpost

  root :to => 'pages#home'
  match '/about' => 'pages#about', :as => :about
  match '/eventlist' => 'pages#events', :as => :eventlist
  match '/corporate' => 'pages#corporate', :as => :corporate
  match '/officers' => 'pages#officers', :as => :officers
  match '/contact' => 'pages#contact', :as => :contact
  match '/blog' => 'blogposts#index', :as => :blog

  match '/admin' => 'pages#admin', :as => :admin
end

app/models/wiki_revision.rb
# == Schema Information
#
# Table name: wiki_revisions
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  content     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  wikipage_id :integer
#

class WikiRevision < ActiveRecord::Base
  attr_accessible :content, :id, :user_id
  belongs_to :wikipage
  belongs_to :user
end

app/controllers/wiki_revisions_controller.rb
include ApplicationHelper
class WikiRevisionsController < ApplicationController
  before_filter :deny_unless_officer
  def new
    @wikipage = Wikipage.find(params[:wikipage_id])
    @latest_revision = WikiRevision.find(@wikipage.current_revision_id)
  end

  def create
    @wikipage = Wikipage.find(params[:wikipage_id])
    revision = WikiRevision.new
    revision.content = params[:content]
    revision.save
    @wikipage.wiki_revisions << revision
    @wikipage.current_revision_id = revision.id
    current_user.wiki_revisions << revision
    @wikipage.save
    redirect_to @wikipage, notice: "Page Edited"
  end

  def index
    @wikipage = Wikipage.find(params[:wikipage_id])
    @revisions = @wikipage.wiki_revisions
  end
end

app/helpers/wiki_revisions_helper.rb
module WikiRevisionsHelper
end

app/views/wiki_revisions/index.html.haml
.row-fluid
  .span2
    %ul.nav.nav-stacked.nav-tabs.sidebak
      %li= link_to "Wiki Index", wikipages_path
      %li= link_to "New Wikipage", new_wikipage_path
      %li.active= link_to "Current Page", @wikipage
      %li= link_to "Edit", new_wikipage_wiki_revision_path(@wikipage)

  .span10
    %ul.revisionlist
      - @revisions.each do |revision|
        %li
          .

app/views/wiki_revisions/new.html.haml
%h1= "Edit #{@wikipage.name}"

.form 
  = form_tag wikipage_wiki_revisions_path, method: :post do
    = label_tag :content
    = text_area_tag :content, @latest_revision.content, class: "wysihtml5"

    = submit_tag "Edit", class: 'btn btn-info btn-medium'