config/routes.rb
Gthkn::Application.routes.draw do

  resources :wikipages do
    resources :wiki_revisions, only: [:new, :create, :index]
  end

  devise_for :users

  resources :users
  resources :blogposts, :only => [:create, :edit, :update, :destroy, :index]
  resources :events
  resources :initiation_requirements, only: [:new, :create, :update]
  resources :auth_codes

  match '/admin/user_admin' => 'users#user_admin', :as => :user_admin
  match '/admin/user_admin/search' => 'users#user_admin_search', :as => :user_admin_search
  match '/admin/initiation' => 'promotions#initiation', as: :initiation

  match '/promotion/member_request/:id' => 'promotions#request_member_promotion',
    as: :member_promote_request
  match '/promotion/member' => 'promotions#member_promote', as: :member_promote

  match '/:controller(/:action(/:id))'

  match '/signup' => 'users#new', :as => :signup

  match '/new_blogpost' => 'blogposts#new', :as => :new_blogpost

  root :to => 'pages#home'
  match '/about' => 'pages#about', :as => :about
  match '/eventlist' => 'pages#events', :as => :eventlist
  match '/corporate' => 'pages#corporate', :as => :corporate
  match '/officers' => 'pages#officers', :as => :officers
  match '/contact' => 'pages#contact', :as => :contact
  match '/blog' => 'blogposts#index', :as => :blog

  match '/admin' => 'pages#admin', :as => :admin
end

app/views/layouts/_admin_navbar_dropdown.html.haml
- if current_user.officer
  %li.dropdown
    %a{"data-target" => '#', "data-toggle" => 'dropdown', :class => 'dropdown-toggle'}
      Administrate
      %b.caret
    %ul.dropdown-menu{role: 'menu'}
      %li= link_to "Auth Codes", auth_codes_path
      %li= link_to "Initiation", initiation_path # TODO: Add Search to Events
      %li= link_to "Knowledge Base", wikipages_path
      %li.divider
      %li= link_to "New Event", new_event_path
      %Li= link_to "New Blogpost", new_blogpost_path
      %li= link_to "User Admin", user_admin_path

app/views/layouts/_blogpost_render.html.haml
- if current_user_is_officer?
  #newpost
    = link_to "New Blogpost", new_blogpost_path, class: "btn btn-info"

- unless @blogposts.nil? or @blogposts.empty?
  .blog
    .pagination-centered= will_paginate @blogposts
    = render partial: 'blogposts/blogpost', collection: @blogposts
    .pagination-centered= will_paginate @blogposts

- else
  .blog
    %h3 No posts currently available.

app/views/layouts/_footer.html.haml
%footer
  %ul
    %li 777 Atlantic Avenue | Atlanta, GA 30332
    %li Van Leer C444
    %li (404) 385-0935

app/views/layouts/_header.html.haml
= render partial: 'layouts/navbar'

- banner = image_tag('hkn-banner.png', class: 'banner')
.banner-container= link_to banner, root_path

app/views/layouts/_navbar.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    = link_to "HKN: Beta Mu", root_path, id: "logo"
    %nav
      %ul.nav.pull-right
        %li= link_to "Blog",    blog_path
        %li= link_to 'About',   about_path
        %li.dropdown
          %a{"data-target" => '#', "data-toggle" => 'dropdown', :class => 'dropdown-toggle'} 
            Events
            %b.caret
          %ul.dropdown-menu{role: 'menu'}
            %li= link_to "Event List", events_path
            %li= link_to "Search", '#' # TODO: Add Search to Events
            - if current_user_is_officer?
              %li.divider
              %li= link_to "New Event", new_event_path
        %li= link_to 'Corporate Relations',   corporate_path
        %li= link_to 'Officers', officers_path
        %li= link_to 'Contact Us', contact_path

        - if user_signed_in?
          = render partial: 'layouts/admin_navbar_dropdown'
          %li= link_to 'Profile', current_user
          %li= link_to 'Log Out', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Log In', new_user_session_path
          %li= link_to 'Sign Up', new_user_registration_path

app/views/layouts/_tinymce_config.html.erb
<%= javascript_include_tag 'tiny_mce/tiny_mce' %>
<script language="javascript" type="text/javascript">
	tinyMCE.init( {
		        // General options
		mode : "textareas",
		theme : "advanced",
		
		theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "left",
    theme_advanced_statusbar_location : "bottom",
    
		width: "700px",
		height: "400px"
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title><%= title %></title>
		<link rel="shortcut icon" href="/favicon.ico" />
		<%= render 'layouts/stylesheets' %>
		
		<%= javascript_include_tag :application %>
		
  </head>
  <body>
		<div class="container">
			
			<%= render 'layouts/header' %>
			
			<div id="content" class="round">
				
				<% flash.each do |key, value| %>
					<div class="flash <%= key %>"><%= value %></div>
				<% end %>
				
				<%= yield %>
			</div>
			
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
  </body>
</html>

app/views/layouts/application.html.haml
%html
  %head
    /[if IE 9] <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    %link{ rel: "shortcut icon", href: "/favicon.ico" }
    = csrf_meta_tags
  %body
    = render partial: 'layouts/header'
    - flash.each do |key, value|
      .flash
        - if key == :success
          .success= value
        - elsif key == :error
          .error= value
        - else
          .notice= value
    .container  

      #content
        = yield
      = render partial: 'layouts/footer'
      = debug(params) if Rails.env.development?